version: '3'

services:
  tests:
    container_name: tests
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: unittest
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    logging:
      driver: none
